DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS passwords;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE logs(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    action INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE passwords(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  service TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  FOREIGN KEY (author_id) REFERENCES user (id)
)

--CREATE TABLE post (
--  id INTEGER PRIMARY KEY AUTOINCREMENT,
--  author_id INTEGER NOT NULL,
--  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--  title TEXT NOT NULL,
--  body TEXT NOT NULL,
--  FOREIGN KEY (author_id) REFERENCES user (id)
--);